[package]
name = "nuncio-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
test-harness = ["nuncio-proto/test-harness"]

[dependencies]
nuncio-proto = { path = "../nuncio-proto" }
tokio.workspace = true
tonic.workspace = true
clap.workspace = true
serde_json.workspace = true
serde.workspace = true
keyring.workspace = true
zeroize.workspace = true
hex.workspace = true
uuid.workspace = true
sha2.workspace = true
tempfile.workspace = true
rustix.workspace = true
futures-util.workspace = true
