name: Feature Request
description: Propose an idea or feature for Nuncio
title: "feat: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thank you for suggesting a feature for Nuncio!
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Feature Proposal
      description: Clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you have considered.
    validations:
      required: false
