[package]
name = "nuncio-proto"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
tonic.workspace = true
tonic-prost.workspace = true
prost.workspace = true
bytes.workspace = true
thiserror.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
protoc-bin-vendored.workspace = true

[dev-dependencies]
tokio.workspace = true
